# Generated by Django 4.2.27 on 2026-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('skills_required', models.TextField(blank=True)),
                ('apply_type', models.CharField(choices=[('google_form', 'Google Form'), ('email', 'Email'), ('in_app', 'In-App Form'), ('external', 'External Link')], max_length=20)),
                ('apply_target', models.TextField(help_text='URL for form/external link, or email address')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('push_on_create', models.BooleanField(default=False, help_text='Send push notification on creation')),
                ('push_sent', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-posted_at'],
            },
        ),
    ]
