# Generated by Django 4.2.27 on 2026-01-23 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='application_job_id_710e05_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-applied_at'], name='application_user_id_786df3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['source'], name='application_source_55874d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
    ]
